namespace BenchTool.Infrastructure.BenchApi.Upstream;

public class ProjectExecAssignResponse
{
	public Value[] value { get; set; }
}

public class Value
{
	public string DemandIndustryPath { get; set; }
	public string RoleTitle { get; set; }
	public int Id { get; set; }
	public string RoleStatus { get; set; }
	public string RoleFlagging { get; set; }
	public string RoleStartDate { get; set; }
	public int RolePercentAllocation { get; set; }
	public string PastStartDate { get; set; }
	public string ClientName { get; set; }
	public int ProjectKey { get; set; }
	public string ProjectName { get; set; }
	public int AssignedRolePriority { get; set; }
	public string AssignedRole { get; set; }
	public string AssignedRoleId { get; set; }
	public string RoleEndDate { get; set; }
	public string RoleFulfillmentEntity { get; set; }
	public int RoleFulfillmentEntityPriority { get; set; }
	public string OrganizationUnitId { get; set; }
	public int RoleLocationTypeKey { get; set; }
	public string RoleLocationTypeName { get; set; }
	public int RoleLocationTypePercentKey { get; set; }
	public string RoleLocationTypePercentName { get; set; }
	public string LocationPreference { get; set; }
	public int LocationPreferenceKey { get; set; }
	public int LocationPreferencePriority { get; set; }
	public string RoleContact { get; set; }
	public string RoleContactEnterpriseId { get; set; }
	public string RoleContactEmail { get; set; }
	public string ClientSupplyDemandSpecialist { get; set; }
	public string ClientSupplyDemandSpecialistEnterpriseId { get; set; }
	public string ClientSupplyDemandSpecialistEmail { get; set; }
	public string Specialty1 { get; set; }
	public int Specialty1Priority { get; set; }
	public int Specialty1ProficiencyKey { get; set; }
	public string Specialty2 { get; set; }
	public int Specialty2Priority { get; set; }
	public string Specialty3 { get; set; }
	public int Specialty3Priority { get; set; }
	public string WorkForce { get; set; }
	public int WorkforcePriority { get; set; }
	public int WorkForceKey { get; set; }
	public string LevelFrom { get; set; }
	public int LevelFromKey { get; set; }
	public int LevelFromSequence { get; set; }
	public string LevelTo { get; set; }
	public int LevelToKey { get; set; }
	public int LevelToSequence { get; set; }
	public string BillCodeFrom { get; set; }
	public string BillCodeTo { get; set; }
	public int LevelPriority { get; set; }
	public int PrimarySkillPriority { get; set; }
	public string PrimarySkill { get; set; }
	public string SecondarySkill { get; set; }
	public int OtherSkillsPriority { get; set; }
	public string OtherSkills { get; set; }
	public string Language { get; set; }
	public int LanguagePriority { get; set; }
	public int NoOfAdditionalRoles { get; set; }
	public string Sold { get; set; }
	public string SoldPercent { get; set; }
	public string Chargeable { get; set; }
	public string Security_NationalRestriction { get; set; }
	public string InterimRole { get; set; }
	public string CountryDescription { get; set; }
	public int CountryId { get; set; }
	public string WorkLocation { get; set; }
	public int ProjectId { get; set; }
	public string RoleOrigination { get; set; }
	public string CandidateListStatus { get; set; }
	public string GeographicAreaDescription { get; set; }
	public int GeographicAreaId { get; set; }
	public string GeographicUnitDescription { get; set; }
	public int GeographicUnitId { get; set; }
	public string CityDescription { get; set; }
	public int CityId { get; set; }
	public string TalentSegment { get; set; }
	public string ClientContractBased { get; set; }
	public string ReadyToHardLock { get; set; }
	public string ReadyToHardLockDate { get; set; }
	public string ExpectedFulfillmentDate { get; set; }
	public string AcceptingResume { get; set; }
	public string IsAFSRole { get; set; }
	public string Description { get; set; }
	public string SourcingChannelInformation { get; set; }
	public string SourcingChannelFulfillmentContact { get; set; }
	public string SourcingChannelFulfillmentContactEnterpriseId { get; set; }
	public string SourcingChannelFulfillmentContactEmail { get; set; }
	public string OpenToContractor { get; set; }
	public string SourcingChannelContractorReason { get; set; }
	public string SourcingChannelIsFilled { get; set; }
	public string SourcingChannelUpdateDate { get; set; }
	public string SourcingChannelUpdateBy { get; set; }
	public string FulfillmentChannelInformation { get; set; }
	public string FulfillmentChannelFulfillmentContact { get; set; }
	public string FulfillmentChannelFulfillmentContactEnterpriseId { get; set; }
	public string FulfillmentChannelFulfillmentContactEmail { get; set; }
	public string FulfillmentChannelContractorName { get; set; }
	public string FulfillmentChannelContractorReason { get; set; }
	public string FulfillmentChannelIsFilled { get; set; }
	public string FulfillmentChannelUpdateDate { get; set; }
	public string FulfillmentChannelUpdateBy { get; set; }
	public int CertificationPriority { get; set; }
	public string Certification { get; set; }
	public string AdditionalRoleInfo1 { get; set; }
	public string AdditionalRoleInfo2 { get; set; }
	//public string FulfillmentChannelTimeStamp { get; set; }
	public string WFTimeStamp { get; set; }
	public int RoleStatusKey { get; set; }
	public int RequestPriorityKey { get; set; }
	public int ContractorReasonKey { get; set; }
	public string FulfillmentChannelIsPrimary { get; set; }
	public string IsFilled { get; set; }
	public string FulfillmentChannelIsPendingJoiner { get; set; }
	public int SourcingChannelKey { get; set; }
	public int RoleContactProfileKey { get; set; }
	public int CSDSProfileKey { get; set; }
	public int CancellationReasonKey { get; set; }
	public int SoldPercentKey { get; set; }
	public string RoleFillDate { get; set; }
	public string RoleReOpenDate { get; set; }
	public int SourcingChannelFulfillmentContactProfileKey { get; set; }
	public string SourcingChannelContractorName { get; set; }
	public string SourcingChannelAgency { get; set; }
	public string SourcingChannelComment { get; set; }
	public int FulfillmentChannelFulfillmentContactProfileKey { get; set; }
	public string FulfillmentChannelAgency { get; set; }
	public string FulfillmentChannelComment { get; set; }
	public string RoleLastUpdatedDate { get; set; }
	public string RoleLastUpdatedBy { get; set; }
	public int FulfillmentChannelKey { get; set; }
	public string LastUpdateSystem { get; set; }
	public int SourchingChannelPkey { get; set; }
	public int FulfillmentChannelPKey { get; set; }
	public int RoleContactPKey { get; set; }
	public int CSDSPKey { get; set; }
	public int WFPKey { get; set; }
	public string IsEFDColUpdated { get; set; }
	public string IsEFDDisabled { get; set; }
	public string RoleFulfillmentDate { get; set; }
	public string SpecialtyNodeId1 { get; set; }
	public string SpecialtyNodeId2 { get; set; }
	public string SpecialtyNodeId3 { get; set; }
	public int LevelFromGroupKey { get; set; }
	public int LevelFromGroupSequence { get; set; }
	public int LevelToGroupKey { get; set; }
	public int LevelToGroupSequence { get; set; }
	public string TalentSegmentCD { get; set; }
	public string ProjectOrgUnitId { get; set; }
	public int RoleStatusSequence { get; set; }
	public int LcrFrom { get; set; }
	public int LcrTo { get; set; }
	public string CreateDate { get; set; }
	public int FilledCandidateProfileKey { get; set; }
	public int ProjectLocationKey { get; set; }
	public string DemandType { get; set; }
	public string AccountabiltyType { get; set; }
	public string Source { get; set; }
	public int DmndTypekey { get; set; }
	public string OpenToGcp { get; set; }
	public string OpenToRecruit { get; set; }
	public string OtherRequirements { get; set; }
	public string DeliveryCenter { get; set; }
	public string DeliveryCenterNodeID { get; set; }
	public string CancellationReason { get; set; }
	public DateTime SubmitDate { get; set; }
	public string SubmitBy { get; set; }
	public int CommonDemandId { get; set; }
	public string ContractorTrackingId { get; set; }
	public string EnableAlternativeFulfillment { get; set; }
	public string IsOpenToWorkday { get; set; }
	public string Region { get; set; }
	public int RegionId { get; set; }
	public int LocId { get; set; }
	public int CommonProjectId { get; set; }
	public string InternalFulfillmentChannelStatus { get; set; }
	public string ContractorFulfillmentChannelStatus { get; set; }
	public string RecruitingFulfillmentChannelStatus { get; set; }
	public int InternalFulfillmentChannelStatusKey { get; set; }
	public int ContractorFulfillmentChannelStatusKey { get; set; }
	public int RecruitingFulfillmentChannelStatusKey { get; set; }
	public string InternalCancellationReason { get; set; }
	public string ContractorCancellationReason { get; set; }
	public string RecruitingCancellationReason { get; set; }
	public int InternalCancellationReasonKey { get; set; }
	public int ContractorCancellationReasonKey { get; set; }
	public int RecruitingCancellationReasonKey { get; set; }
	public string IsPreIdentifiedContractor { get; set; }
	public int GCPAppStatKey { get; set; }
	public string GCPApprovalStatus { get; set; }
	public int AbacusProjectKey { get; set; }
	public int AbacusProjectLocationKey { get; set; }
	public string AbacusProjectName { get; set; }
	public string RoleApproval { get; set; }
	public string TrackingCode { get; set; }
	public string GDNFlag { get; set; }
	public string IsAvaRole { get; set; }
	public string ContractorReason { get; set; }
	public string ContractorAgency { get; set; }
	public string ContractorName { get; set; }
	public string ContractorRequisitionId { get; set; }
	public string ContractorCompanyCode { get; set; }
	public object ContractorExpectedFulfillmentDate { get; set; }
	public string ContractorExpenseApprover { get; set; }
	public string ContractorTimecardApprover { get; set; }
	public string CXAgent { get; set; }
	public object NowFilled { get; set; }
	public string P104Approver { get; set; }
	public string ContractorSecondaryContact { get; set; }
	public string ContractorSingleCareerLevelId { get; set; }
	public string ContractorSingleCareerLevel { get; set; }
	public string ContractorWbsChargeCode { get; set; }
	public string WorkLocationPostalCode { get; set; }
	public string WorkOrderId { get; set; }
	public string ContractorPurge { get; set; }
	public string RecruitingCompanyCode { get; set; }
	public string AdditionalLocations { get; set; }
	public string AdditionalScheduleDetails { get; set; }
	public string AdditionalScreeningsRequired { get; set; }
	public string ScreeningRequirements { get; set; }
	public string AuthorizedBy { get; set; }
	public object AuthorizedByDate { get; set; }
	public string OverallOfferApprover { get; set; }
	public string BusinessAreaId { get; set; }
	public string BusinessArea { get; set; }
	public string BusinessGroup { get; set; }
	public string CostCenter { get; set; }
	public string Education { get; set; }
	public string EmployeeStatus { get; set; }
	public string EstimatedTravelPercentage { get; set; }
	public string FederalJobCategory { get; set; }
	public string JobDescription { get; set; }
	public string JobLevel { get; set; }
	public string JobType { get; set; }
	public string JoinerName { get; set; }
	public string NOCCode { get; set; }
	public string OvertimeCode { get; set; }
	public string PartTimePercentage { get; set; }
	public object PendingJoiner { get; set; }
	public string PreferredInterviewers { get; set; }
	public string QualificationsAndRequirement { get; set; }
	public string RecruitingContact { get; set; }
	public string RecruitingReason { get; set; }
	public string RecruitingRequisitionId { get; set; }
	public object RecruitInternalOnly { get; set; }
	public string RecruitingRoleId { get; set; }
	public string RecruitingRoleNm { get; set; }
	public string RoleFamilyId { get; set; }
	public string RoleFamilyName { get; set; }
	public string Schedule { get; set; }
	public string RecruitingSecondaryContact { get; set; }
	public string Shift { get; set; }
	public string RecruitingSingleCareerLevelId { get; set; }
	public string RecruitingSingleCareerLevel { get; set; }
	public string CareerLevelGroupId { get; set; }
	public string CareerLevelGroup { get; set; }
	public string TalentSegmentId { get; set; }
	public string TalentSegmentNm { get; set; }
	public string RecruitingWbsChargeCode { get; set; }
	public object RecruitingExpectedFulfillmentDate { get; set; }
	public string RecruitingPurge { get; set; }
	public string CSDSTimestamp { get; set; }
	public string ExceptionFlag { get; set; }
	public string FulfillmentChannelTimestamp { get; set; }
	public string RoleContactTimestamp { get; set; }
	public string SourcingChannelIsPendingJoiner { get; set; }
	public string SourcingChannelIsPrimary { get; set; }
	public string SourcingChannelTimestamp { get; set; }
	public string SpecialtyParentNodeId1 { get; set; }
	public string SpecialtyParentNodeId2 { get; set; }
	public string SpecialtyParentNodeId3 { get; set; }
	public string Timestamp { get; set; }
	public string WorkforceTimestamp { get; set; }
	public object[] FulfillmentChannelAddComment { get; set; }
	public object[] SkillList { get; set; }
	public object[] SourcingChannelAddComment { get; set; }
	public object DeleteOverride { get; set; }
	public object PriorityTag { get; set; }
	public object Unit { get; set; }
	public int SDOFactoryKey { get; set; }
	public object FurtherDeploymentDetails { get; set; }
	public object RequesterInfo { get; set; }
	public object UserEnterpriseId { get; set; }
	public int UserProfileKey { get; set; }
	public int ContractReasonKey { get; set; }
	public object ActionTag { get; set; }
	public object SoldKey { get; set; }
	public object IsFromRoleMaintenance { get; set; }
	public int CapabilityFrameworkNodeId { get; set; }
	public object[] CertificationList { get; set; }
	public int SkillNodeId { get; set; }
	public int SkillKey { get; set; }
	public int SkillProficiencyKey { get; set; }
	public int OrgUnitId { get; set; }
	public object[] LanguageList { get; set; }
	public object SourcingChannelIsPending { get; set; }
	public object FulfillmentChannelIsPending { get; set; }
	public object[] Specialty1List { get; set; }
	public object[] Specialty2List { get; set; }
	public object[] Specialty3List { get; set; }
	public object ErrorMessage { get; set; }
	public bool IsMassUpload { get; set; }
	public object SpecialtyNodes { get; set; }
	public object SkillKeys { get; set; }
	public object EfdCalculateTag { get; set; }
	public bool FromSubscriber { get; set; }
	public object[] AssignmentCopies { get; set; }
	public object CandidateName { get; set; }
	public object CandidateStatus { get; set; }
	public object PeopleKey { get; set; }
	public object ContractorApproved { get; set; }
	public object RecruitingApproved { get; set; }
	public object IQNComplete { get; set; }
	public object ATASComplete { get; set; }
	public object IsStatusUpdated { get; set; }
	public int IsChangedRHL { get; set; }
	public int ParentRoleId { get; set; }
	public int CopyKey { get; set; }
	public object ContractorStatus { get; set; }
}