namespace ConsoleApp.POCO;

public class ProjectMainResponse
{
	public int Id { get; set; }
	public string ProjectName { get; set; }
	public int PWUID { get; set; }
	public int ProjectStatusKey { get; set; }
	public string ProjectStatus { get; set; }
	public int ClientKey { get; set; }
	public string Client { get; set; }
	public string ClientClassification { get; set; }
	public string IsClientValid { get; set; }
	public string ProjectCreateDate { get; set; }
	public string ProjectStartDate { get; set; }
	public string ProjectEndDate { get; set; }
	public int SoldPercentageKey { get; set; }
	public string SoldPercentage { get; set; }
	public string IsSold { get; set; }
	public string IsChargeable { get; set; }
	public int GeoKey { get; set; }
	public string GeographyUnit { get; set; }
	public int CountryKey { get; set; }
	public string Country { get; set; }
	public int AreaKey { get; set; }
	public string ProjectWorkLocation { get; set; }
	public int PriorityKey { get; set; }
	public string Priority { get; set; }
	public string NationalSecurity { get; set; }
	public string ClientContractBased { get; set; }
	public string IsProjectIndustry { get; set; }
	public string ProjectIndustryNodeId { get; set; }
	public string Industry { get; set; }
	public string DemandIndustryNm { get; set; }
	public string DemandIndustryPath { get; set; }
	public int SdoFactoryKey { get; set; }
	public string SdoFactory { get; set; }
	public int PortfolioKey { get; set; }
	public string Portfolio { get; set; }
	public string AddDeploymentDetail { get; set; }
	public string FurtherDeploymentDetail { get; set; }
	public string ProjectDescription { get; set; }
	public string OperatingGroup { get; set; }
	public string OperatingUnit { get; set; }
	public string ClientServiceGroup { get; set; }
	public string ProjectTimestamp { get; set; }
	public string ConversionStatus { get; set; }
	public string ProjectSupervisingEntityID2 { get; set; }
	public string IsInternal { get; set; }
	public string StaffAug { get; set; }
	public string ProjectOrgUnitID { get; set; }
	public string OperatingGroupID { get; set; }
	public string OperatingUnitID { get; set; }
	public string ClientServiceGroupID { get; set; }
	public string ProjectSupervisingEntity2 { get; set; }
	public object UpdateBy { get; set; }
	public object ActionIndicator { get; set; }
	public int UserProfileKey { get; set; }
	public int AlternateAddressNumber { get; set; }
	public object Purge { get; set; }
	public int ProjectSupervisingEntityIndicator { get; set; }
	public object ProjectSupervisingEntityUpdate { get; set; }
	public object OldProjectSupervisingEntityId1 { get; set; }
	public object OldProjectSupervisingEntityId2 { get; set; }
	public object ErrorMessage { get; set; }
	public int ErrorNumber { get; set; }
	public string IndustryPath { get; set; }
	public string OpportunityID { get; set; }
}